--liquibase formatted sql;

--changeset dima:1
create table if not exists locations (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    address varchar(255) not null,
    capacity integer not null,
    description varchar(255)
);
--rollback drop table if exists locations;