--liquibase formatted sql;

--changeset dima:1
create table if not exists users (
    id bigint generated by default as identity primary key ,
    login varchar(255) unique not null ,
    password_hash varchar(255) not null ,
    age integer not null ,
    role varchar(255) not null
);
--rollback drop table if exists users;