--liquibase formatted sql;

--changeset dima:1
create table if not exists events(
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    max_places integer not null,
    cost integer not null,
    duration integer not null,
    date_start date not null,
    occupied_places integer,
    location_id bigint not null,
    owner_id bigint not null,
    event_status varchar(255) not null
);
--rollback drop table if exists events;

--changeset dima:2
alter table events
alter column date_start type timestamp with time zone;
--rollback drop