--liquibase formatted sql;

--changeset dima:1
create table if not exists user_register_event (
    id bigint generated by default as identity primary key ,
    user_id bigint not null ,
    event_id bigint not null ,
    count_tickets integer not null,

    constraint fk_register_user
        foreign key (user_id)
        references users(id),

    constraint fk_register_event
        foreign key (event_id)
        references events(id),

    constraint uk_user_event
        unique (user_id, event_id)
)
--rollback drop table if exists user_register_event;

